### ISSUE TITLE
Document how to use ds9

### ISSUE THREAD

**Issue by dlakaplan** [growth-astro/growth-hub-notebook#8]

**Comment by dlakaplan** [comment]
@igorandreoni put this into https://github.com/growth-astro/growth-school-2020/blob/master/docs/users_giude_jupyterhub.md
Jus tested and it seems to work.

During the school, you may want to visualize astronomical images using the ds9 application. To open a ds9 window, open a new desktop from the Hub main page (click on the New dropdown menu in the top-right corner of the page, then click on Desktop). A new desktop should open in a new tab. There, open a terminal and type ds9 & to start a new ds9 window. You can open an image from the File menu of the ds9 GUI, or you can open an image directly from command line by typing on the terminal, for example, ds9 growth/module_name/data/image_name.fits

**Comment by mjuric** [comment]
If it'd be friendlier, we could add a ds9 desktop icon.

It's really easy (shortcuts are simple ini-style text files).

**Comment by dlakaplan** [comment]
Yes, I think that would help.

**Comment by mjuric** [comment]
Here's how to do it -- write a (text) file named `ds9.desktop`, with the following contents:
```
[Desktop Entry]
Version=1.0
Type=Application
Name=DS9
Exec=....path_to_ds9_executable.... %f
Icon=....path_to_ds9_icon.svg...
MimeType=application/fits;
EOF
```
As to how to do it -- best to try it out manually on JupyterHub using the terminal first, and then include it into the Dockerfile.

PS: Not sure what to use for the ds9 icon -- I suspect you cloud take [this](https://pbs.twimg.com/profile_images/3346340935/f858a23cdd0fa7f7c2f485ff5c0ef65e_400x400.png) and just convert it to `.svg` (and it's possible `.png` will also just work).

Refs:
* https://wiki.archlinux.org/index.php/desktop_entries
* https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#recognized-keys
